[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
sibyl_oracle = "gVaLAXxsYPLdmJnzL5HyuA57jCrSvjv93Lprw8VGtfu"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy"
upgrade = "anchor upgrade"


[toolchain]
anchor_version = "0.30.1"
